before_install:
  - curl -sf https://test.docker.com | sh
  - docker --version

dist: bionic

language: bash

env:
  global:
    - DOCKER_CLI_EXPERIMENTAL=enabled
    - PLATFORMS=linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64
  matrix:
    - VARIANT=alpine
    - VARIANT=debian

stages:
  - name: test
    if: tag IS present OR branch = master
  - name: push
    if: tag IS present OR branch = master

script:
  - echo "$DOCKER_PASSWORD" | docker login -u nunofgs --password-stdin
  - docker run --privileged linuxkit/binfmt:v0.7
  - docker buildx create --use
  - docker buildx build
    --platform $PLATFORMS
    --build-arg "VERSION=$TRAVIS_BRANCH"
    --file "$VARIANT/Dockerfile"
    --tag nunofgs/octoprint:$TRAVIS_BRANCH-$VARIANT
    `if [ -n "$TRAVIS_TAG" ]; then echo "--tag nunofgs/octoprint:$VARIANT"; fi`
    `if [ -n "$TRAVIS_TAG" ] && [ "$VARIANT" = "debian" ]; then echo "--tag nunofgs/octoprint:latest"; fi`
    `if [ "$VARIANT" = "debian" ]; then echo "--tag nunofgs/octoprint:$TRAVIS_BRANCH"; fi`
    --push
    .
