before_install:
  - sudo apt-get install docker-ce=18.02.0~ce-0~ubuntu
  - mkdir ~/.docker && echo '{ "experimental":"enabled" }' > ~/.docker/config.json
  - docker --version

language: bash

env:
  matrix:
    - ARCH=amd64
    - ARCH=arm32v6

stages:
  - name: test
    if: tag IS present OR branch = master
  - name: push
    if: tag IS present OR branch = master

script:
  - docker run --rm --privileged multiarch/qemu-user-static:register --reset
  - docker build -t "nunofgs/octoprint:$TRAVIS_BRANCH-$ARCH" --build-arg "arch=$ARCH" --build-arg "version=$TRAVIS_BRANCH" .
  - docker login -u=nunofgs -p="$DOCKER_PASSWORD"
  - docker push "nunofgs/octoprint:$TRAVIS_BRANCH-$ARCH"

jobs:
  include:
    - stage: push
      script:
        - docker login -u=nunofgs -p="$DOCKER_PASSWORD"
        - docker pull "nunofgs/octoprint:$TRAVIS_BRANCH-amd64"
        - docker pull "nunofgs/octoprint:$TRAVIS_BRANCH-arm32v6"
        - >
          docker manifest create "nunofgs/octoprint:$TRAVIS_BRANCH" "nunofgs/octoprint:$TRAVIS_BRANCH-amd64" "nunofgs/octoprint:$TRAVIS_BRANCH-arm32v6" &&
          docker manifest annotate "nunofgs/octoprint:$TRAVIS_BRANCH" "nunofgs/octoprint:$TRAVIS_BRANCH-arm32v6" --os linux --arch arm --variant v6 &&
          docker manifest push "nunofgs/octoprint:$TRAVIS_BRANCH"
        - >
          if [ -n "$TRAVIS_TAG" ]; then
            docker tag "nunofgs/octoprint:$TRAVIS_BRANCH-amd64" nunofgs/octoprint:latest &&
            docker push nunofgs/octoprint:latest
          fi
        - >
          if [ -n "$TRAVIS_TAG" ]; then
            docker manifest create "nunofgs/octoprint:latest" "nunofgs/octoprint:$TRAVIS_BRANCH-amd64" "nunofgs/octoprint:$TRAVIS_BRANCH-arm32v6" &&
            docker manifest annotate "nunofgs/octoprint:latest" "nunofgs/octoprint:$TRAVIS_BRANCH-arm32v6" --os linux --arch arm --variant v6 &&
            docker manifest push "nunofgs/octoprint:latest"
          fi
